# see more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "rost"
version = "0.2.0"
authors = ["Jacob Swanson <me@jacob-swanson.com>"]
edition = "2018"

[dependencies]
rlibc = "1.0.0"
bootloader = "0.9.8"